<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Scalar.AspNetCore" Version="2.17.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Produtos.Api.ServiceDefaults\Ecommerce.Produtos.Api.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Ecommerce.Produtos.Application\Ecommerce.Produtos.Application.csproj" />
    <ProjectReference Include="..\Ecommerce.Produtos.Infrastructure\Ecommerce.Produtos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
