<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Produtos.Domain\Ecommerce.Produtos.Domain.csproj" />
    <ProjectReference Include="..\Ecommerce.Produtos.Infrastructure\Ecommerce.Produtos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
